### ISSUE TITLE
Are my VCF files formatted incorrectly?

### ISSUE THREAD

**Issue by halessi** [bio-ontology-research-group/DeepSVP#1]
Hi, this might be a bad issue to post here because it's mainly with AnnotSV I guess, but if you could help it would be much appreciated.

I am getting this error when running annotation.sh:

`No SV to annotate in the SVinputFile - Exit without error.`

I have tried multiple vcf files to no avail. Thanks.

edit: just to note, the file size of the vcf is not 0.

**Comment by leechuck** [comment]
@azzatha could you provide a working sample VCF file so that @halessi can compare against the VCF that does not work?

**Comment by leechuck** [comment]
@halessi but could it be that your VCF file only contains SNVs and not structural variants?

**Comment by halessi** [comment]
@leechuck Thank you so much for your reply.

I am pretty sure there are structural variants in the file, though I am not certain. A test vcf file would be super helpful, for whatever reason I haven't been super successful in locating one.

If this is the case, what is the typical process for generating a SV VCF from WES data?

Thanks for your help.

**Comment by leechuck** [comment]
We usually use WGS data to call structural variants, using Manta (https://github.com/Illumina/manta) or GATK (https://github.com/broadinstitute/gatk-sv) or lumpy or delly. For WES, it is more difficult to identify structural variants and I doubt your WES VCF file contains structural variants unless you used some of the research tools available for calling SVs from exome data (https://github.com/geocarvalho/sv-cnv-studies has a number of references including tools to call SVs/CNVs from exomes).

**Comment by halessi** [comment]
I see, apologies and thank you for your help.

**Comment by azzatha** [comment]
Hi @halessi 
Thank you for testing the tool! :)

Thank you @leechuck for your comment.

We already included an example file in [README](https://github.com/bio-ontology-research-group/DeepSVP/blob/master/README.md), more specifically in [data](https://bio2vec.cbrc.kaust.edu.sa/data/DeepSvp/). 
```deepsvp -d data/ -i example_annotsv.tsv -p HP:0003701,HP:0001324,HP:0010628,HP:0003388,HP:0000774,HP:0002093,HP:0000508,HP:0000218 -m cl -maf 0.01 -ag max -o example_output.txt```

Best,
