### ISSUE TITLE
Help for install

### ISSUE THREAD

**Issue by lgmgeo** [bio-ontology-research-group/DeepSVP#6]
Hi,

I would like to install DeepSVP with the following command:
```
pip3 install deepsvp
```
but I have this error message:
```
Collecting tensorflow==2.3.0
  Could not find a version that satisfies the requirement tensorflow==2.3.0 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.12.0, 1.12.2, 1.12.3, 1.13.1, 1.13.2, 1.14.0)
No matching distribution found for tensorflow==2.3.0
```

Actually, I've had difficulties with the following requirement:
```
pip3 install tensorflow==2.3.0   
Collecting tensorflow==2.3.0
  Could not find a version that satisfies the requirement tensorflow==2.3.0 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.12.0, 1.12.2, 1.12.3, 1.13.1, 1.13.2, 1.14.0)
No matching distribution found for tensorflow==2.3.0
```

Thank you for any help you can provide me,
Véronique

**Comment by azzatha** [comment]
Hello @lgmgeo

Sorry about this issue, this is due to different versions existing, could you please try again now? 

Thank you,
Azza.

**Comment by lgmgeo** [comment]
Hi Azza,

Thank you for coming back to me.
Unfortunately, it still doesn't work...
![image](https://user-images.githubusercontent.com/49909073/149919742-435629c4-2e82-4ba4-ad91-2726dae720b3.png)
Any other ideas?

Véronique

**Comment by xiucz** [comment]
Hi,  @azzatha  How about updating to the lastest AnnotSV version (v3.1)?

**Comment by lgmgeo** [comment]
Hi Azza,

Thank you for your help. Everything is working well now with `pip3 install deepsvp`!

If it can help some other users, I used conda to create the good environment:
```
conda create -n deepsvp-py38-pip2031 python=3.8 pip=20.3.1
conda activate deepsvp-py38-pip2031
pip3 install deepsvp
```
Best,
Véronique
PS: Perhaps it could be useful to add this requirement (pip version) in the README.md?

**Comment by lgmgeo** [comment]
> Hi, @azzatha How about updating to the lastest AnnotSV version (v3.1)?

Question posted in a new issue (https://github.com/bio-ontology-research-group/DeepSVP/issues/7)

**Comment by azzatha** [comment]
> Hi Azza,
> 
> Thank you for your help. Everything is working well now with `pip3 install deepsvp`!
> 
> If it can help some other users, I used conda to create the good environment:
> 
> ```
> conda create -n deepsvp-py38-pip2031 python=3.8 pip=20.3.1
> conda activate deepsvp-py38-pip2031
> pip3 install deepsvp
> ```
> 
> Best, Véronique PS: Perhaps it could be useful to add this requirement (pip version) in the README.md?

Thank you so much @lgmgeo! I updated the README based on your recommendation for creating the environment first.
